version: "3"
services:
  api:
    build:
      context: .
      dockerfile: dockerfile-api
    container_name: api
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://admin:admin@mongodb:27017/cliente-oculto-auth
    restart: always