version: "3"
services:
  mongodb:
    build: .
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - my-network
    restart: always
    volumes:
      - mongodb-data:/data/db
  api:
    build: ./api
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:admin@mongodb:27017/cliente-oculto-auth
    networks:
      - my-network
    restart: always
networks:
  my-network:
volumes:
  mongodb-data: